export const PRODUCTS = [
  {
    id: 1,
    productName: "SONY FX3 Full-frame Cinema Line Body Only",
    price: 3999.99,
    productImage: "./assets/products/fx3.png",
    discountedPrice: 3599.99,
  },
  {
    id: 2,
    productName: "Hollyland Cosmo C1 SDI/HDMI Wireless",
    price: 784.99,
    productImage: "./assets/products/cosmo-c1.png",
    discountedPrice: 699.99,
  },
  {
    id: 3,
    productName:
      "Sony Alpha a7C Mirrorless Digital Camera with 28-60mm Lens (Silver)",
    price: 2037.99,
    productImage: "./assets/products/a7c.jpg",
    discountedPrice: 1799.99,
  },
  {
    id: 4,
    productName: "Godox SB-GUE Octa 95 Umbrella Softbox with Grid",
    price: 102.99,
    productImage: "./assets/products/godox.png",
    discountedPrice: 101.99,
  },
  {
    id: 5,
    productName:
      "Fujifilm X-S10 Mirrorless Digital Camera Kit XC 15-45mm f3.5-5.6 OIS PZ",
    price: 1299.99,
    productImage: "./assets/products/fujicam.png",
    discountedPrice: 1199.99,
  },
  {
    id: 6,
    productName: "Sony PXW-Z90T 4K HDR XDCAM with Fast Hybrid AF",
    price: 2393.99,
    productImage: "./assets/products/sonycamcorder.jpg",
    discountedPrice: 2199.99,
  },
  {
    id: 7,
    productName: "Sony FE 35mm f1.4 GM Lens",
    price: 1259.99,
    productImage: "./assets/products/sonylens.jpg",
    discountedPrice: 1199.99,
  },
  {
    id: 8,
    productName: "Fujifilm XF 50mm f1.0 R WR Lens",
    price: 1511.99,
    productImage: "./assets/products/fujilens.png",
    discountedPrice: 1399.99,
  },
  {
    id: 9,
    productName: "Sony BC-QZ1 Battery Charger",
    price: 101.99,
    productImage: "./assets/products/sonycharger.png",
    discountedPrice: 100.99,
  },
  {
    id: 10,
    productName: "Sony NP-FW50 Rechargeable Battery Pack",
    price: 174.99,
    productImage: "./assets/products/sonybatt.png",
    discountedPrice: 169.99,
  },
  {
    id: 11,
    productName:
      "Canon EOS RP Mirrorless Digital Camera with 24-105mm f4-7.1 IS STM Lens",
    price: 1299.99,
    productImage: "./assets/products/canoneos24-105.png",
    discountedPrice: 1199.99,
  },
  {
    id: 12,
    productName: "Canon LP-E17 Lithium-Ion Battery Pack",
    price: 109.99,
    productImage: "./assets/products/canonbattery.png",
    discountedPrice: 107.99,
  },
  {
    id: 13,
    productName: "Canon RF 50mm f1.8 STM Lens",
    price: 269.99,
    productImage: "./assets/products/canonlensrf50.png",
    discountedPrice: 249.99,
  },
  {
    id: 14,
    productName:
      "Canon EOS R Mirrorless Digital Camera with 24-105mm f4-7.1 STM Lens",
    price: 1826.99,
    productImage: "./assets/products/canoneos.jpg",
    discountedPrice: 1699.99,
  },
  {
    id: 15,
    productName: "Fujifilm Lens Hood LH-XF16",
    price: 199.99,
    productImage: "./assets/products/fujihood.png",
    discountedPrice: 197.99,
  },
  {
    id: 16,
    productName: "Fujifilm XF 70-300mm f4-5.6 R LM OIS WR Lens",
    price: 787.99,
    productImage: "./assets/products/fujifilmxf.png",
    discountedPrice: 699.99,
  },
];
